services:
  - type: web
    name: emebel-api
    env: python
    plan: free
    buildCommand: pip install -r emebel_api/requirements.txt
    startCommand: cd emebel_api && bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENV_NAME
        value: production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: WEBAPP_URL
        sync: false
